name: Metrics
on:
  schedule: [{cron: "0 */12 * * *"}]
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
        - uses: lowlighter/metrics@latest
          token: ${{ secrets.METRICS_TOKEN }}
          user: ysathyasai
          template: classic
          base: header, activity, community, repositories
          plugin_achievements: yes
          plugin_achievements_display: compact
